### ISSUE TITLE
Couple of places on Microsoft site it still says Microsoft S2C2F instead of OpenSSF S2C2F

### ISSUE THREAD

**Issue by mlieberman85** [ossf/s2c2f#21]
There was some confusion from a few folks I spoke to that were unsure if it was an OpenSSF project or a Microsoft project. It says OpenSSF in some places but in other Microsoft S2C2F. I think it would help with contributions if they knew it was an official OpenSSF project.

In https://www.microsoft.com/en-us/securityengineering/opensource/osssscframeworkguide

> The Microsoft S2C2F is based on three core concepts—control all artifact inputs, continuous process improvement, and scale:

> The Microsoft S2C2F tools were developed to secure how developers consume OSS today at scale without requiring a central internal registry or central governance body.

**Comment by adriandiglio** [comment]
Thanks! The 2 places you cited have been fixed. https://www.microsoft.com/en-us/securityengineering/opensource/osssscframeworkguide
