### ISSUE TITLE
Annotate maturity graphic with requirement ID's

### ISSUE THREAD

**Issue by joshuagl** [ossf/s2c2f#46]
The maturity graphic is an excellent overview of the practices recomemnded at each maturity level. It could be even more useful for helping folks navigate and orient to the specififcation if the requirment ID's of the practices were indicated for each practice.

Further, I would recommend a stronger correlation to between the text in the diagram and the requirement titles. I recognise why the diagram can't easily use the full text title, but perhaps the sentence used in the diagram could be the start of the title and bolded in the title in the requirements table?
i.e.,  the diagram lists "Use public package managers" and the requirements title becomes "**Use public package managers** trusted by your organization (i.e. NuGet.org, npmjs.com, PyPi.org, etc.)".

Alternatively, the requirements table could be broken down into title + description + benefit, or the description moved into the benefit column, so that the title text matches the diagram exactly.

Finally, the graphic is missing the most recently added AUD-5.

**Comment by joshuagl** [comment]
I'd make the change myself and submit a PR, but I can't find the "source" from which the maturity diagram is generated.

**Comment by joshuagl** [comment]
Here's a (garishly) annotated copy of the diagram I used to help orient my own reading of the s2c2f spec:
<img width="1015" alt="maturity-level-white-bkg" src="https://github.com/ossf/s2c2f/assets/13888612/b4d54a7a-0990-42cf-a056-1c9f7ee37b1c">

**Comment by adriandiglio** [comment]
Hi @joshuagl , thanks for this feedback! Here is the proposed updated graphic. Does this work for you? 
![image](https://github.com/ossf/s2c2f/assets/55258689/47b77d30-ad5b-40f9-b94a-45a7c7e88acb)

**Comment by joshuagl** [comment]
Thanks @adriandiglio ! AUD-5 is still missing from level 3, but otherwise this LGTM!

**Comment by joshuagl** [comment]
This graphic is great, please submit a PR to include it in the repo 😄

**Comment by adriandiglio** [comment]
Closed with PR
