### ISSUE TITLE
Can s2c2f  be extended and cover AI Use cases ? 

### ISSUE THREAD

**Issue by victorjunlu** [ossf/s2c2f#58]
Can s2c2f  be extended and cover AI Use cases ?

**Comment by adriandiglio** [comment]
Great question @victorjunlu! I suggest that we create a workstream to explore and think through this problem. I've created a blank doc to help get this started ([Google doc link](https://docs.google.com/document/d/1UyvpC52feo7dZsDee2vQLWIMOjoD-dfAIr-cG0dqoHc/edit?usp=sharing)). We'll look for volunteers to lead and/or contribute to this workstream

**Comment by adriandiglio** [comment]
Closing this issue with creation of Issue #60
